name: Releases

env:
  PLUGIN_NAME: logseq-plugin-ai-helper

on:
  push:
    tags:
      - "v*" # Runs when a version tag (e.g., v1.0.1) is pushed
  workflow_dispatch: # Allows manual execution

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.1

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Install zip utility
        uses: montudor/action-zip@v1

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
